{% set name = "chainlit" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/chainlit-{{ version }}.tar.gz
  sha256: 3467b6e1740cb7a437e020496b07a7f433c777d7c8a241c5f45d981e29458f17

build:
  entry_points:
    - chainlit = chainlit.cli:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9,<4.0
    - poetry-core
    - pip
    - wheel
  run:
    - python >=3.9,<4.0.0
    - httpx 
    - literalai 
    - dataclasses-json <0.7.0,>=0.6.7
    - fastapi 
    - starlette <0.38.0,>=0.37.2
    - uvicorn <0.26.0,>=0.25.0
    - python-socketio <6.0.0,>=5.11.0
    - aiofiles <24.0.0,>=23.1.0
    - syncer 
    - asyncer ==0.0.7
    - nest-asyncio 
    - click 
    - tomli
    - pydantic 
    - python-dotenv ==1.0.1 
    - uptrace 
    - watchfiles <0.21.0,>=0.20.0
    - filetype 
    - lazify 
    - packaging <24.0,>=23.1
    - python-multipart 
    - pyjwt 
    - numpy <2.0,>=1.26

test:
  imports:
    - chainlit
  commands:
    - pip check
    - chainlit --help
  requires:
    - pip

about:
  home: https://github.com/Chainlit/chainlit
  summary: Build Conversational AI.
  license: Apache-2.0
  license_file: LICENSE
  dev_url: https://github.com/Chainlit/chainlit
  doc_url: https://github.com/Chainlit/chainlit/blob/main/README.md

extra:
  anaconda-services:
    ref: https://anaconda.zendesk.com/agent/tickets/49522
    reason: Client request
  recipe-maintainers:
    - ianaobi
    - bkreider
